version: 2.1
aliases:
  - &restore-cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "gradle.properties" }}
        - v1-dependencies-
  - &save-cache
    save_cache:
      paths:
        - ~/.gradle/wrapper
        - ~/.gradle/caches
      key: v1-dependencies-{{ checksum "gradle.properties" }}


  - &defaults
    docker:
      - image: cimg/openjdk:11.0

commands:
  run-with-dependencies:
    parameters:
      steps:
        description: "Steps that will be executed after loading dependencies"
        type: steps
    steps:
      - checkout
      - *restore-cache
      - steps: << parameters.steps >>

jobs:
  create-cache:
    <<: *defaults
    steps:
      - checkout
      - *restore-cache
      - run: ./gradlew dependencies
      - *save-cache
  tests:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew test coveralls --info
  lint:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: ./gradlew ktlintCheck --info
  deploy:
    <<: *defaults
    steps:
      - run-with-dependencies:
          steps:
            - run: git config user.email "circle-ci@pipeline.com"
            - run: git config user.name "Circle CI"
            - run: ORG_GRADLE_PROJECT_signingKey=$(echo $ORG_GRADLE_PROJECT_signingKey | base64 -d) ./gradlew core:publish -Pversion=$(echo $CIRCLE_BRANCH | cut -f2 -d-)
            - run: ./gradlew closeAndReleaseRepository
            - run: ./gradlew core:release -Prelease.useAutomaticVersion=true -PreleaseVersion=$(echo $CIRCLE_BRANCH | cut -f2 -d-)
            - run: git checkout master
            - run: git pull origin $CIRCLE_BRANCH
            - run: git push
workflows:
  version: 2.1
  build-test-verify-deploy:
    jobs:
      - create-cache
      - tests:
          requires:
            - create-cache
      - lint:
          requires:
            - create-cache
      - deploy:
          requires:
            - tests
            - lint
          filters:
            branches:
              only:
                - /^release-.*$/